language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev cython
install:
  - pip install numexpr
  - pip install -r dev_requirements.txt
  - pip install coveralls
  - python setup.py develop
  - pushd examples/plugin
  - python setup.py develop
  - popd
script:
  - flake8 .
  - coverage run -m unittest discover
  - python setup.py build_sphinx
after_success:
  - coveralls
