language: python
sudo: false
python:
- '2.7'
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python-pip
    - libhdf5-serial-dev
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.ccache"
before_install:
- ccache -s
- export PATH=/usr/lib/ccache:${PATH}
- pip install --upgrade pip
install:
- pip install numexpr
- pip install -r dev_requirements.txt
- python setup.py develop
- pushd examples/plugin
- python setup.py develop
- popd
script:
- flake8 .
- coverage run -m unittest discover -p test*
- sphinx-build -W doc/source doc/build/sphinx
after_success:
- pip install codecov
- codecov
notifications:
  slack:
    secure: a3aAlsxs2uPa1ggrDQouECqMGfR9DaZQBOVUmdGeOK6LHq+Pta/KbgUbiwA42c3QbR9WfI+J3oRuC9ZrZDo6d/DmobTCBTutWsTPs/LIJIZVfdbvYyJWzzeFTE9ca4iwHiQiZlG3d6EVQYVEf3cWuE89o0YEmRLmxAy99MPAtWM=
