language: python
sudo: false
python:
  - "2.7"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python-pip
    - libhdf5-serial-dev
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
install:
  - pip install numexpr
  - pip install -r dev_requirements.txt
  - python setup.py develop
  - pushd examples/plugin
  - python setup.py develop
  - popd
script:
  - flake8 .
  - coverage run -m unittest discover -p test*
  - python setup.py build_sphinx
after_success:
  - pip install codecov
  - codecov