language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev
install:
  - pip install cython==0.20
  - pip install numexpr
  - pip install tables
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - flake8 .
  - coverage run -m unittest discover
  - coverage report
