build: false
shallow_clone: true
environment:

  global:
    distutils_use_sdk: 1

  matrix:
    - python: "C:/Python27-x64"
      sdkver: "v7.0"

cache:
  - '%localappdata%\pip\cache'

init:
  - ps: $Env:sdkbin = "C:\Program Files\Microsoft SDKs\Windows\" + $Env:sdkver + "\Bin"
  - ps: $Env:sdkverpath = "C:/Program Files/Microsoft SDKs/Windows/" + $Env:sdkver + "/Setup/WindowsSdkVer.exe"
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:sdkbin + ";" + $Env:path
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', $Env:TEMP + '/get-pip.py')
  - ps: python $Env:TEMP + '/get-pip.py'
  - ps: pip --version
  - cmd /v:on /e:on /c ".\appveyor-install.cmd"
test_script:
  - cmd /v:on /e:on /c ".\appveyor-test.cmd"
